version: '3'

tasks:
  dev:
    deps:
      - for: [ls, css]
        task: task-{{.ITEM}}
  task-ls:
    cmds:
      - live-server --open=web --port=8888
  task-css:
    cmds:
      - tailwindcss -c web/tailwind.config.js -i web/input.css -o web/output.css --watch