version: '3'

tasks:
  dev:
    deps:
      - for: [ls, css]
        task: task-{{.ITEM}}
  task-ls:
    cmds:
      - live-server --open=docs --port=8888
  task-css:
    cmds:
      - tailwindcss -c docs/tailwind.config.js -i docs/input.css -o docs/output.css --watch