version: '3'

tasks:
  dev:
    deps:
      - for: [ls, css]
        task: task-{{.ITEM}}
  task-ls:
    cmds:
      - live-server --port=8888
  task-css:
    cmds:
      - tailwindcss -i input.css -o output.css --watch